package com.github.epietras220.todo.list;

public enum MenuState {

    MAIN_MENU, CREATE_ENTRY, COMPLETE_ENTRY, EXTEND_DEADLINE, COMPLETED_TASK_LIST_VIEW, INCOMPLETE_TASK_LIST_VIEW, ALL_TASK_LIST_VIEW, SAVE_AS_CSV_FILE, READ_FROM_CSV_FILE
}
